#! /bin/bash
cd .. && cd ./cpuminer-opt/ && ./cpuminer -a lyra2z330  -u baka -p bond --no-stratum --no-getwork --no-longpoll --coinbase-addr=HLtwjQtK2frqrEoQ9B1Eo6PXxaxuNmEj2D -b 0 -o http://54.191.214.162:29200 -t 28
